@startuml UC03_Asignar_Tecnico
left to right direction
skinparam actorStyle awesome
skinparam shadowing false
skinparam packageStyle rectangle

actor Supervisor
rectangle Sistema {
  usecase "Asignar Técnico" as UC03
}

Supervisor --> UC03 : Seleccionar ticket y técnico
UC03 --> Sistema : Vincular tecnico_id y supervisor_id
@enduml
